config/routes.rb
Badhoc::Application.routes.draw do

  match 'boards/:board_id/posts/page/:page' => 'posts#index'

  namespace :api do 
    resources :boards
    resources :posts
    resources :comments
  end

  resources :categories

  resources :posts do
    post :lock
    post :unlock
    post :stickify
    post :unstickify
    resources :comments
  end

  resources :boards do
    resources :posts
  end

  resources :bans

  devise_for :admins

  resources :picwalls

  root :to => 'categories#index'

end

app/views/shared/_admin_box.html.erb
<div class='admin span-24 last' style="display:none;">
	<p>
		<%= link_to 'Manage Bans', bans_path %>
	</p>
</div>

app/views/shared/_ban_bar.html.erb
Client IP: 

<% if post.active_ban? %>
	<strike><%= post.client_ip %></strike>
	Client currently banned for <%= distance_of_time_in_words(Time.now, post.active_ban.expires_at)%>
<% else %>
<%= post.client_ip %>
<%= link_to '1 day ban', bans_path(:ban => {:client_ip => post.client_ip, 
																						:expires_at => 1.day.from_now, 
																						:reason => 'Submitted from Post Page'}), 
																						:remote => true, 
																						:method => 'post' %>
																						
<%= link_to '5 day ban', bans_path(:ban => {:client_ip => post.client_ip, 
																						:expires_at => 5.days.from_now, 
																						:reason => 'Submitted from Post Page'}), 
																						:remote => true, :method => 'post' %>
																						
<%= link_to 'Permaban!', bans_path(:ban => {:client_ip => post.client_ip, 
																						:permanent => true, :reason => 'Submitted from Post Page'}), 
																						:remote => true, 
																						:method => 'post', 
																						:confirm => 'Are you sure?' %>
<% end %>

app/views/shared/_board_box.html.erb
<div class='board_box span-5'>
  <%= link_to board.name, board_posts_path(board), :class => 'board_name' %>
	<div class='board_info'>
		<p class='board_description'><%= board.description %></p>
		<p class='board_posts_count'>Posts:<%= board.children_count %></p>
		<p class='board_last_active'>Last Active: <%= timeago(board.updated_at) %></p>
		<p class='board_buttons'>
			<%= link_to image_tag('icons/information.png', :title => 'Info'), board_path(board) %>	
				<% if admin_signed_in? %>
					<%= link_to image_tag('icons/application_edit.png', :title => 'Edit'), edit_board_path(board) %>
					<%= link_to image_tag('icons/delete.png', :title => 'Delete'), board, 
                      :confirm => 'Are you sure? This will delete all boards, posts and comments under this category!',
                      :method => :delete %>
				<% end %>
		</p>
	</div>
</div>

app/views/shared/_thumbbar.html.erb
<div id='thumbbar' class='span-24 last'>
	<div class='prepend-2 span-3'><%= link_to(image_tag('icons/Home.png', :title => 'Home', :size => '64x64'), '/') %></div>
	<div class='span-3'><%= link_to(image_tag('icons/Slideshow.png', :title => 'Picwalls', :size => '64x64'), '/picwalls') %></div>
	<div class='span-3 prepend-12 last'><%= link_to(image_tag('icons/octocat.png', :title => 'Source', :size => '64x64'), 'http://github.com/skord/badhoc') %></div>
</div>

app/views/shared/_tripcode_name_email.html.erb
<% if post.active_ban?%>
<strong class='<%= 'authenticated ' if post.tripcoded? %> quiet'>
	<%= post.name %><%= " - User Banned: #{post.active_ban.reason}" %>
</strong>
<% elsif post.email.empty? || post.email == 'noko' || post.email == 'sage' %>
	<strong class='<%= 'authenticated ' if post.tripcoded? %>'>
		<%= post.name %>
	</strong>
<% else %>
	<strong class='<%= ' authenticated ' if post.tripcoded? %>'>
		<%= mail_to post.email, post.name, :encode => 'javascript' %>
	</strong>
<% end %>