config/routes.rb
Badhoc::Application.routes.draw do

  match 'boards/:board_id/posts/page/:page' => 'posts#index'

  namespace :api do 
    resources :boards
    resources :posts
    resources :comments
  end

  resources :categories

  resources :posts do
    post :lock
    post :unlock
    post :stickify
    post :unstickify
    resources :comments
  end

  resources :boards do
    resources :posts
  end

  resources :bans

  devise_for :admins

  resources :picwalls

  root :to => 'categories#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  include TripcodeHelper

  # It used to be that the post threshold was the entire site. That's fixed as of this commit. 
  # Active post threshold is now per board, hence lowering the number by a factor of 10 here. 
  # Still a small issue though, this needs to be moved to the board model for post aging somehow, 
  # but you end up screwing up the named scopes below. So for now the active threshold for posts
  # is still a global (across every board) value. This is reflected in the weird mix of instance
  # and singleton methods at the bottom until I get that mentally cleared up. 

  ACTIVE_POST_THRESHOLD = 100
  acts_as_list :scope => :board
  
  cattr_reader :per_page
  @@per_page = 10

  has_many :comments, :dependent => :destroy
  belongs_to :board, :counter_cache => true, :touch => true
  
  before_validation :set_tripcoded_name
  before_save       :pull_image_geometries
  

  # Hey awesome, you're running the delayed_job branch for asynchronous awesomness!
  # The cleanup portion of the following filter calls Board#cleanup!.
  # Rather than looking over there, I'll just mention here that it throws a destroy
  # job in queue for each Post that's expired (not a destroy_all, the AREL stuff doesn't
  # work as expected, maybe I'm wrong). Some of of those are doomed to fail since I'm 
  # not deduplicating or throwing up a flag for "put in the kill me queue", but it's
  # no big deal.
  
  after_create      :increment_board_attachments_size, :cleanup!
  
    
  before_destroy    :decrement_board_attachments_size
  
  
  has_attached_file :postpic,
                    :styles => {:small => '200x200#',
                                :thumb => '64x64#'}

  # Bitches don't know bout my named scopes
  scope :has_attachment, where('postpic_file_name is not ?', nil)
  scope :no_attachment, where('postpic_file_name is ?', nil)
  scope :sticky, where('sticky = ?', true)
  scope :not_sticky, where('sticky = ?', false)


  def set_tripcoded_name
    self.name = tripcode(self.name)
  end

  def pull_image_geometries
    tempfile = self.postpic.queued_for_write[:original]
    unless tempfile.nil?
      dimensions = Paperclip::Geometry.from_file(tempfile)
      self.image_width = dimensions.width
      self.image_height = dimensions.height
    end    
  end

  def increment_board_attachments_size
    if self.postpic.size != nil
      board = self.board
      board.increment!(:attachments_size, by = self.postpic.size)
    end
  end

  def decrement_board_attachments_size
    if self.postpic.size != nil
      board = self.board
      board.decrement!(:attachments_size, by = self.postpic.size)
    end
  end
  
  validates_presence_of :name, :message => "can't be blank"

  validates_attachment_presence :postpic, :message => "can't be blank. That means you have to upload something."
  validates_attachment_size :postpic, :less_than => 5.megabytes
  validates_attachment_content_type :postpic, :content_type => ['image/jpeg', 'image/png', 'image/gif']
  
  validate :user_banned
  
  def user_banned
    errors.add("You Are Banned From Posting for the Following Reason: ","#{Ban.find_by_client_ip(self.client_ip).reason}") unless Ban.active.find_by_client_ip(self.client_ip) == nil
  end

  validates_presence_of :message

  # validate :posting_too_quickly, :on => :create
  # 
  # def posting_too_quickly
  #   errors.add("Error Posting", "You are attempting to post too quickly. Posts are allowed once a minute.") if Post.order('created_at DESC').find_by_client_ip(self.client_ip).created_at > Time.now - 1.minute
  # end
  
  def poster_post_count
    Post.find_all_by_name(self.name).count
  end
  
  def limit_locked?
    self.comments_count >= 100
  end
  
  def lock
    self.update_attribute(:locked, true)
  end
  
  def unlock
    self.update_attribute(:locked, false)
  end
  
  def stickify
    self.update_attribute(:sticky, true)
  end
  
  def unstickify
    self.update_attribute(:sticky, false)
  end
  
  def active_ban
    @ban_record ||= Ban.active.find_by_client_ip(self.client_ip)
  end
  
  def active_ban?
    active_ban != nil
  end
  

  #
  # These are weird, and the english doesn't exactly match the SQL. Basically, you have
  # to read it not as "Created at less than five minutes ago", but rather
  # "The time this was created at is before 5 minutes ago."
  #
  # There are a plethora of cleanup methods rather than doing this the rails way so I can
  # easily explain it to people for the decision they need to make regarding delayed jobs.

  def cleanup
    self.board.cleanup
  end

  def cleanup!
    self.board.cleanup!
  end
  

  attr_accessible :name, :email, :subject, :message, :password, :postpic
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController

  respond_to :xml, :json

  def index
    @posts = Post.select('id, created_at, updated_at, name, tripcoded, email, subject, message, board_id, postpic_content_type, postpic_file_name, postpic_file_size, postpic_updated_at')
    respond_with @posts do |format|
      format.xml  {render :xml => @posts}
      format.json {render :json => @posts}
    end
  end
  
  def show
    @post = Post.select('id, created_at, updated_at, name, tripcoded, email, subject, message, board_id, postpic_content_type, postpic_file_name, postpic_file_size, postpic_updated_at').find(params[:id])
    respond_with @post do |format|
      format.xml  {render :xml => @post}
      format.json {render :json => @post}
    end
  end
  
  def create
    @post = Post.new(params[:post])
    
    respond_to do |format|
      if @post.save
        format.xml { render :xml => @post, :status => :created, :location => @post }
      else
        format.xml { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # Yeah, there's a lot of caching methods here, its much of an attempt to cover different cases.
  # Because of CSRF protection and user sessions, the response headers really only do anything
  # at all if you're stripping cookies at the reverse proxy session. If you setup that way,
  # I'd recommend a filter to avoid the /admin path and other admin actions you can find in 
  # rake routes. See, isn't RESTfulness super? TL;DR: Cache headers mean nothing unless you've 
  # configured your reverse proxy to toss cookies. 
  #
  # There is a conditional get for index, which will throw a 304 unless the 
  # content in the block and the last modified date has changed.
  
  #
  # In the views there are quite a bit of partial fragments cached. The render times for comments 
  # and post names, emails etc are a bit high and there are quite a few of these.

  respond_to :html, :js

  before_filter :authenticate_admin!, :except => [:index, :show, :new, :create]
  
  # GET /posts
  # GET /posts.xml
  def index
    @board = board
    @post = board.posts.new

    if stale?(:last_modified => @board.updated_at.utc, :etag => @posts)
    @posts = board.active_posts.paginate :order => 'sticky DESC, position ASC', :page => params[:page], :per_page => 10, :include => :comments
    @all_posts = board.active_posts
      respond_with [board, @posts] do |format|
        format.html {
          # Since pagination is done via JS if available, this mostly targets robots. 
          # It's still set pretty low because the #1 landing spot is board_posts_path
          # in html format.
          response.headers['Cache-Control'] = 'public, max-age=15'
        }
        format.atom {
          # For varnish. Anyone that cares this much about an atom feed should find another way.
          response.headers['Cache-Control'] = 'public, max-age=60'
        }
        format.js
        format.iphone {render :layout => false}
      end
    end
    
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id], :include => :comments)
    @comment = @post.comments.new

    if stale?(:last_modified => @post.updated_at.utc, :etag => @post)
      respond_to do |format|
        format.html
        format.atom {
          # For varnish. Anyone that cares this much about an atom feed should find another way.
          response.headers['Cache-Control'] = 'public, max-age=60'
        }
        format.js
        format.iphone {render :layout => false}
      end
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = board.posts.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /posts/1/edit
  def edit
    @post = board.posts.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = board.posts.new(params[:post])
    @client_ip = request.remote_ip
    @post.client_ip = @client_ip

    respond_to do |format|
      if @post.save
        session[:my_name] = params[:post][:name]
        @post.move_to_top
        format.html { 
          if @post.email == 'noko'
            redirect_to(board_posts_path)
          else
            redirect_to(board_post_path(board, @post)) 
          end
          }
      else
        format.html { render 'new' }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = board.posts.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        expire_action :action => :show
        format.html { redirect_to(board_posts_path, :notice => 'Post was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = board.posts.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(board_posts_path) }
    end
  end
  
  def lock
    @post = Post.find(params[:post_id])
    @post.lock
    @post.touch
    respond_to do |format|
      if @post.save
        format.html { redirect_to(post_path(@post), :notice => 'Post locked.') }
        format.js
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def unlock
    @post = Post.find(params[:post_id])
    @post.unlock
    @post.touch
    respond_to do |format|
      if @post.save
        format.html { redirect_to(post_path(@post), :notice => 'Post unlocked.') }
        format.js
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def stickify
    @post = Post.find(params[:post_id])
    @post.stickify
    @post.touch
    respond_to do |format|
      if @post.save
        format.html { redirect_to(board_posts_path(@post.board), :notice => 'Post stickified.') }
        format.js
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  def unstickify
    @post = Post.find(params[:post_id])
    @post.unstickify
    @post.touch
    respond_to do |format|
      if @post.save
        format.html { redirect_to(board_posts_path(@post.board), :notice => 'Post unstickified.') }
        format.js
      else
        format.html { render :action => "edit" }
      end
    end
  end

  
  private
  
  def board
    @board ||= Board.find_by_slug(params[:board_id])
  end
end

app/helpers/api/posts_helper.rb
module Api::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= semantic_form_for([@post.board, @post], :html => {:multipart => true}) do |f| %>
	<% if @post.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

	    <ul>
	    <% @post.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>
	<% f.inputs do %>
	  <%= f.input :name, :input_html => {:value => form_name_app_helper} %>
	  <%= f.input :email, :as => :string %>
	  <%= f.input :subject %>
	  <%= f.input :message %>
		<%= f.input :postpic, :hint => 'Max 5Mb. jpg/png/gif accepted' %>
	<% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_pagination.html.erb
<%= will_paginate @posts %>

app/views/posts/_post.html.erb
<div id='<%= dom_id(post) %>' class='post prepend-1 append-1 span-22 last '>

	<div class='postpic span-6'>
		<% if post.postpic? %>
			<%= link_to(image_tag(post.postpic.url(:small), :size => '200x200'),post.postpic.url, :class => 'postpic', :target => "_blank") %>
		<% else %>
			<p>None</p>
		<% end %>
		<%= render :partial => 'post_comment_thumbs', :locals => {:post => post} %>
	</div>
	<div class='post-info span-16 last'>
		<%= render :partial => 'shared/tripcode_name_email', :locals => {:post => post}%>
		<dfn><%= post.subject %></dfn>
		<em><%= timeago(post.created_at) %></em>
		<% if post.sticky? %>
			<%= image_tag "icons/note.png", :size => '16x16', :title => "Sticky Post", :class => 'sticky_post' %>
		<% end %>
		<% if post.locked? %>
			<%= image_tag "icons/lock.png", :size => '16x16', :title => "Locked Post", :class => 'locked_post' %>
		<% end %>
		<br />
		<%= render :partial => 'post_file_info_bar', :locals => {:post => post} %>
		<br />
		Post: <%= post.id %>
		<%= link_to('Show/Reply', post) if controller.action_name == 'index'%>
		<%= link_to "Picwall", picwall_path(post)%>
		<%= render :partial => 'post_admin_bar', :locals => {:post => post}%>
		<br />
		<br />
		<% if controller.action_name == 'index'%>
			<div class='<%= 'locked quiet' if post.locked? %>'>
				<%= user_text_markdown(post.message, 500)%>
			</div>
		<% else %>
			<div id='<%= dom_id(post)%>' class='<%= 'locked quiet' if post.locked? %>'>
				<%= user_text_markdown(post.message)%>
			</div>
		<% end %>
		<br />
		<em id='post_comments_count'><%= pluralize post.comments_count, 'comment' %>...</em>
		<br />
		<% if controller.action_name == "index"%>
			<table>
			<% post.comments.order('created_at DESC')[0..8].each do |comment| %>
				<tr>
					<td><%= render :partial => 'shared/tripcode_name_email', :locals => {:post => comment}%></td>
					<td><%= timeago(comment.created_at) %></td>
					<td><%= strip_tags user_text_markdown(comment.message,40) %></td>
				</tr>
			<% end %>
			</table>
		<% end %>
	</div>
</div>

app/views/posts/_post_admin_bar.html.erb
<div class="admin post_admin_bar" style="display:none;">
	<p>
		Admin: 
		<%= link_to (image_tag "icons/page_edit.png", :size => "16x16", :title => "Edit"), edit_board_post_path(post.board, post) %>
		<%= link_to (image_tag "icons/page_delete.png", :size => "16x16", :title => "Delete"), board_post_path(post.board, post), :confirm => "Are you sure?", :method => :delete %>
		<% unless post.locked? %>
			<%= link_to((image_tag "icons/lock_open.png", :size => "16x16", :title => "Lock", :class => "lock"), post_lock_path(post), :method => :post) %>
		<% else %>
			<%= link_to((image_tag "icons/lock.png", :size => "16x16", :title => "Unlock", :class => 'unlock'), post_unlock_path(post), :method => :post) %>
		<% end %>
		<% unless post.sticky? %>
			<%= link_to((image_tag "icons/note_add.png", :size => "16x16", :title => "Stickify", :class => 'stick'), post_stickify_path(post), :method => :post) %><%=  %>
		<% else %>
			<%= link_to((image_tag "icons/note_delete.png", :size => "16x16", :title => "Unstickify", :class => 'unstick'), post_unstickify_path(post), :method => :post) %><%=  %>
		<% end %>
		<br />
	</p>
</div>

app/views/posts/_post_comment_thumbs.html.erb
<div class='post-comment-thumbs'>
	<% for comment in post.comments.order('created_at DESC').select {|x| x.commentpic_file_name != nil}[0..8] %>
		<% unless comment.commentpic_processing? %>
			<%= link_to(image_tag(comment.commentpic.url(:thumb), :size => '64x64', :class => 'comment_thumbnail'), comment.commentpic.url, :target => '_blank')%>
		<% end %>
	<% end %>
</div>

app/views/posts/_post_file_info_bar.html.erb
<em><%= post.postpic.original_filename %>/<%= number_to_human_size(post.postpic.size) %>/<%= post.image_width %>x<%= post.image_height %></em>

app/views/posts/_posts.html.erb
<div class='prepend-1 last'>
<%= render 'pagination' %>
</div>

<% cache @posts do %>
	<%= render @posts %>
<% end %>

<div class='prepend-1 last'>
<%= render 'pagination' %>
</div>

app/views/posts/index.html.erb
<%= auto_discovery_link_tag(:atom, "#{board_posts_path(@board)}.atom", {:title => 'Posts Atom'}) %>

<p class='large prepend-1 last'>
<%= link_to 'Home', '/'%> \
<%= link_to @board.category.name, @board.category %> \
<%= link_to @board.name, board_posts_path(@board) %> \
All Posts
</p>

<div class='prepend-21 last'>
	<%= button_to_function 'New Post', "$('#new_post_form').toggle();" %>
</div>

<div id='new_post_form' style="display:none;" class='last'>
	<%= render 'form' %>
</div>

<div id='posts'>
<%= render 'posts' %>
</div>

app/views/posts/index.iphone.erb
<ul title="Posts" selected="true">
  <% @posts.each do |post| %>
  <li>
    <a href="<%= post_path(post) + '.iphone' %>">
      <% if post.subject == '' %>
        <em>No Subject...</em>
      <% else %>
        <%= post.subject %>
      <% end %>
      <span>
        Active <%= time_ago_in_words(post.updated_at) %> ago, 
        <%= pluralize(post.comments_count, 'comment') %>
      </span>
    </a> 
  </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.iphone.erb
<div class = "panel" title = "<%= @post.subject %>" selected = "true">
  <center><%= image_tag @post.postpic.url(:small) %></center>
  <fieldset>
    <div class="row">
      <label>Post</label>
      <span><%= @post.id %></span>
    </div>    
    <div class="row">
      <label>From</label>
      <span><%= @post.name %></span>
    </div>
    <div class="row">
      <label>Subject</label>
      <span><%= truncate(@post.subject, :length => 20, :omission => '...') %></span>
    </div>
    <div class="row">
      <label>Submitted</label>
      <span><%= time_ago_in_words(@post.created_at) %> ago</span>
    </div>
    <div class="row">
      <label>Replies</label>
      <span><%= @post.comments_count %></span>
    </div>   
    <div class="row">
      <p><%= user_text_markdown(@post.message) %></p>
    </div>     
  </fieldset>
  <% @post.comments.each do |comment| %>
    <%= render :partial => 'comments/comment.iphone', :locals => {:comment => comment} %>
  <% end %>
</div>

app/views/posts/stickify.js.erb
$("#<%= dom_id(@post) %> .post_admin_bar").html('<%= escape_javascript(render(:partial => 'post_admin_bar', :locals => {:post => @post})) %>');
$(".post_admin_bar").show();
$("div#post_<%= @post.id %>.post div.post-info em abbr.timeago").after(' <img alt="Note" class="sticky_post" height="16" src="/images/icons/note.png" title="Sticky Post" width="16">');

$(document).ready(function () {
	$('img.stick').click(function() {
		$.post($(this).parent()[0] + '.js');
		return false;
	});
});

$(document).ready(function () {
	$('img.unstick').click(function() {
		$.post($(this).parent()[0] + '.js');
		return false;
	});
});

app/views/posts/unlock.js.erb
$("#<%= dom_id(@post) %> .post_admin_bar").html('<%= escape_javascript(render(:partial => 'post_admin_bar', :locals => {:post => @post})) %>');
$(".post_admin_bar").show();
$("div#post_<%= @post.id %>.post img.locked_post").remove();

$(document).ready(function () {
	$('img.lock').click(function() {
		$.post($(this).parent()[0] + '.js');
		return false;
	});
});

$(document).ready(function () {
	$('img.unlock').click(function() {
		$.post($(this).parent()[0] + '.js');
		return false;
	});
});

app/views/posts/unstickify.js.erb
$("#<%= dom_id(@post) %> .post_admin_bar").html('<%= escape_javascript(render(:partial => 'post_admin_bar', :locals => {:post => @post})) %>');
$(".post_admin_bar").show();
$("div#post_<%= @post.id %>.post img.sticky_post").remove();

$(document).ready(function () {
	$('img.stick').click(function() {
		$.post($(this).parent()[0] + '.js');
		return false;
	});
});

$(document).ready(function () {
	$('img.unstick').click(function() {
		$.post($(this).parent()[0] + '.js');
		return false;
	});
});