config/routes.rb
Badhoc::Application.routes.draw do

  match 'boards/:board_id/posts/page/:page' => 'posts#index'

  namespace :api do 
    resources :boards
    resources :posts
    resources :comments
  end

  resources :categories

  resources :posts do
    post :lock
    post :unlock
    post :stickify
    post :unstickify
    resources :comments
  end

  resources :boards do
    resources :posts
  end

  resources :bans

  devise_for :admins

  resources :picwalls

  root :to => 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  # This is strictly for categorization of the different boards. 
  has_many :boards, :dependent => :destroy
  validates_presence_of :name
  validates_uniqueness_of :name
  
  attr_accessible :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :authenticate_admin!, :except => [:index, :show]

  respond_to :html

  def index
    @categories = Category.all(:include => :boards)
    if stale?(:last_modified => Board.order('updated_at DESC').first.updated_at.utc, :etag => @categories)
      # respond_with @categories
      respond_to do |format|
        format.html
        format.iphone
      end
    end
  end

  def show
    @category = Category.find(params[:id])
    respond_to do |format|
      format.html
      format.iphone {render :layout => false}
    end
  end

  def new
    @category = Category.new
    respond_with @category
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(categories_path, :notice => 'Category was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(categories_path, :notice => 'Category was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_board_box.html.erb
<div class='board_box span-5'>
<%= link_to board.name, board_posts_path(board), :class => 'board_name' %>
	<div class='board_info'>
		<p class='board_description'><%= board.description %></p>
		<p class='board_posts_count'>Posts:<%= board.posts_count + board.posts.all.collect {|x| x.comments_count}.sum %></p>
		<p class='board_last_active'>Last Active: <%= time_ago_in_words(board.last_active) + ' ago' unless board.last_active == ''%></p>
		<p class='board_buttons'>
			<%= link_to image_tag('icons/information.png', :title => 'Info'), board_path(board) %>	
				<% if admin_signed_in? %>
					<%= link_to image_tag('icons/application_edit.png', :title => 'Edit'), edit_board_path(board) %>
					<%= link_to image_tag('icons/delete.png', :title => 'Delete'), board, 
																:confirm => 'Are you sure? This will delete all boards, posts and comments under this category!', 
																:method => :delete %>
				<% end %>
		</p>
	</div>
</div>

app/views/categories/_category.html.erb
<div class='last category prepend-2 append-2'>
	<p class='category_admin'>
	<%= category.name %>
		<% if admin_signed_in? %>
			<%= link_to image_tag('icons/application_edit.png', :title => 'Edit'), edit_category_path(category) %>
			<%= link_to image_tag('icons/delete.png', :title => 'Delete'), category,
                  :confirm => 'Are you sure?',
                  :method => :delete %>
		<% end %>
	</p>
	<% category.boards.each do |board|%>
		<%= render :partial => 'shared/board_box', :locals => {:board => board} %>
	<% end %>
</div>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% if iphone_user_agent? %>
<h1>Hey, it looks like you have a mobile device. <%= link_to "Try the mobile version!", '/.iphone' %></h1>
<% end %>

<div id='categories'>
  <%= render @categories %>
</div>

<% if admin_signed_in? %>
  <div class='span-22 prepend-2'>
    <%= link_to 'New Category', new_category_path %>
    <%= link_to 'New Board', new_board_path %>
  </div>
<% end %>

app/views/categories/index.iphone.erb
<ul title="Categories" selected="true"> 
  <% @categories.each do |category| %>
    <li><%= link_to category.name, category_path(category) + '.iphone' %></li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<div class='span-20 append-2 prepend-2'>
  <h1>New category</h1>

  <%= render 'form' %>

  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<div class='last prepend-2'>
  <p class='large'>
    <%= link_to 'Home', '/'%> \
    <%= @category.name %>
  </p>
</div>

<div class='last category prepend-2 append-2'>
  <% @category.boards.each do |board|%>
	  <%= render :partial => 'shared/board_box', :locals => {:board => board} %>
  <% end %>
</div>

<div class='last span-20 prepend-2'>
  <% if admin_signed_in? %>
    <%= link_to 'Edit', edit_category_path(@category) %> |
  <% end %>
  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.iphone.erb
<ul title="Boards" selected="true">
  <% @category.boards.each do |board| %>
   <li><%= link_to board.name, board_posts_path(board) + '.iphone' %></li>
  <% end %>
</ul>