config/routes.rb
Badhoc::Application.routes.draw do

  match 'boards/:board_id/posts/page/:page' => 'posts#index'

  namespace :api do 
    resources :boards
    resources :posts
    resources :comments
  end

  resources :categories

  resources :posts do
    post :lock
    post :unlock
    post :stickify
    post :unstickify
    resources :comments
  end

  resources :boards do
    resources :posts
  end

  resources :bans

  devise_for :admins

  resources :picwalls

  root :to => 'categories#index'

end

app/models/picwall.rb
class Picwall < Post
end

app/controllers/picwalls_controller.rb
class PicwallsController < ApplicationController

  before_filter :authenticate_admin!, :except => [:index, :show, :new, :create]
  # GET /picwalls
  # GET /picwalls.xml
  def index
    @picwalls = Picwall.paginate :order => 'updated_at DESC', :page => params[:page], :per_page => 10, :include => :comments
    @picwalls_iphone = Picwall.limit(10).order(:position)

    if stale?(:last_modified => @picwalls.last.updated_at.utc, :etag => @picwalls)
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @picwalls }
        format.js
      end
    end
  end

  # GET /picwalls/1
  # GET /picwalls/1.xml
  def show
    @picwall = Picwall.find(params[:id], :include => :comments)

    if stale?(:last_modified => @picwall.updated_at.utc, :etag => @picwall)
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @picwall }
      end
    end
  end

  # GET /picwalls/new
  # GET /picwalls/new.xml
  def new
    @picwall = Picwall.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @picwall }
    end
  end

  # GET /picwalls/1/edit
  def edit
    @picwall = Picwall.find(params[:id])
  end

  # POST /picwalls
  # POST /picwalls.xml
  def create
    @picwall = Picwall.new(params[:picwall])

    respond_to do |format|
      if @picwall.save
        format.html { redirect_to(@picwall, :notice => 'Picwall was successfully created.') }
        format.xml  { render :xml => @picwall, :status => :created, :location => @picwall }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @picwall.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /picwalls/1
  # PUT /picwalls/1.xml
  def update
    @picwall = Picwall.find(params[:id])

    respond_to do |format|
      if @picwall.update_attributes(params[:picwall])
        format.html { redirect_to(@picwall, :notice => 'Picwall was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @picwall.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /picwalls/1
  # DELETE /picwalls/1.xml
  def destroy
    @picwall = Picwall.find(params[:id])
    @picwall.destroy

    respond_to do |format|
      format.html { redirect_to(picwalls_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/picwalls_helper.rb
module PicwallsHelper
end

app/views/picwalls/_form.html.erb
<%= form_for(@picwall) do |f| %>
  <% if @picwall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picwall.errors.count, "error") %> prohibited this picwall from being saved:</h2>

      <ul>
      <% @picwall.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/picwalls/_pagination.html.erb
<div class='pagination span-21 prepend-3 last'>
	<%= page_entries_info @picwalls %>     
	<%= will_paginate @picwalls %>
</div>

app/views/picwalls/_picwalls.html.erb
<%= render 'pagination'%>
<div class='span-21 prepend-3 last'>
	<% @picwalls.each do |picwall|%>
		<div class='span-2 last'>
			<%= link_to(image_tag(picwall.postpic.url(:thumb), :size => '64x64', :title => picwall.subject), picwall_path(picwall)) %>
			<% picwall.comments.each do |comment|%>
				<%= link_to(image_tag(comment.commentpic.url(:thumb), :size => '64x64'), picwall_path(picwall)) if comment.commentpic? %>
			<% end %>
		</div>
	<% end %>
</div>
<%= render 'pagination'%>

app/views/picwalls/edit.html.erb
<h1>Editing picwall</h1>

<%= render 'form' %>

<%= link_to 'Show', @picwall %> |
<%= link_to 'Back', picwalls_path %>

app/views/picwalls/index.html.erb
<div id='picwalls'>
	<%= render 'picwalls' %>
</div>

app/views/picwalls/index.iphone.erb
<% @picwalls_iphone.each do |picwall| %>
<%= link_to (image_tag picwall.postpic.url(:thumb), :class => 'picwall-postpic'), picwall.postpic.url %>
 <% picwall.comments.each do |comment| %>
 <%= link_to (image_tag comment.commentpic.url(:thumb), :class => 'picwall-commentpic'), comment.commentpic.url %>
 <% end %>
<% end %>

app/views/picwalls/index.js.erb
$('#picwalls').html("<%= escape_javascript(render("picwalls"))%>");
document.title = "<%= escape_javascript("Picwalls - Page #{params[:page] || 1}")%>";
$("#picwalls").css({opacity:1.0});

app/views/picwalls/new.html.erb
<h1>New picwall</h1>

<%= render 'form' %>

<%= link_to 'Back', picwalls_path %>

app/views/picwalls/show.html.erb
<p id="notice"><%= notice %></p>


<div class='span-6 prepend-2'>
	<%= link_to(image_tag(@picwall.postpic.url(:small), :size => '200x200'), @picwall.postpic.url, :target => '_blank', :class => 'fancybox', :rel => 'picwall') %>
</div>
<div class='span-15 prepend-1 last'>
	<div class='span-4'>
		Original Post: 
		<br />
		Picture Comments:
		<br />
		Text Comments:
	</div>
	<div class='span-4 last'>
		<%= link_to @picwall.board.name, board_posts_path(@picwall.board) %> \ <%= link_to "Post #{@picwall.id}", post_path(@picwall) %>
		<br />
		<%= @picwall.comments.has_attachment.count %>
		<br />
		<%= @picwall.comments.no_attachment.count %>
	</div>
</div>
<div class='span-8 prepend-1 last'>
	<br />
	<br />
	<em>Click any picture to open a gallery. Use your mousewheel or trackpad to scroll through. Click anywhere to close the slideshow. Right click options are for the full size image, which may be bigger than what appears.</em>
</div>
<div class='span-22 prepend-2 last'>
	<% @picwall.comments.not_processing.each do |comment|%>
		<%= link_to(image_tag(comment.commentpic.url(:small)), comment.commentpic.url, :target => '_blank', :class => 'fancybox', :rel => 'picwall') if comment.commentpic? %>
	<% end %>
</div>